name: Deploy to cdn branch

on:
  push:
    branches:
      - master

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for Git to git push
    name: Publish lists
    runs-on: ubuntu-latest
    steps:
      - name: Clone Anti-Circumvention-Filterlist
        uses: actions/checkout@v3
        with:
            ref: cdn
      - name: Copy filter lists to cdn
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 https://github.com/uBlockO/Anti-Circumvention-Filterlist.git $TMPDIR
          pushd $TMPDIR > /dev/null
          ./tools/make-anticircumventionfilterlist.sh
          popd > /dev/null
          cp $TMPDIR/acf.txt ./acf.txt
      - name: Patch last-updated field
        run: |
          DATE=$(date -Ru)
          for f in $(git diff --name-only); do
            STAT=$(git diff --numstat $f | sed -r '/^1\s+1\s+/d')
            if [[ -n $STAT ]]; then
              sed -ir "0,/^! Last modified: /s/^\(! Last modified: \)%timestamp%/\\1$DATE/" $f
            else
              git checkout -q $f
            fi
          done
      - name: Commit changes (if any)
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "gitHub-actions bot"
            git config user.email "<>"
            git commit -m "Update modified filter lists"
            git push origin cdn
          fi
